version: '3.8'

services:
  # The "Sender" or "Attacker" node
  node-a:
    image: csi-lab-nc:1
    container_name: nc-lab-sender
    stdin_open: true
    tty: true
    networks:
      - lab-net

  # The "Receiver" or "Listener" node
  node-b:
    image: csi-lab-nc:1
    container_name: nc-lab-receiver
    stdin_open: true
    tty: true
    networks:
      - lab-net

networks:
  lab-net:
    driver: bridge